POST http://localhost:8090/api/sale/invoices/los_heroes/1
Content-Type: application/json

[
  {
    "id": 1,
    "quantity": 1,
    "product": {
      "id":1,
      "name": "Salchipapa Mixta",
      "costPrice": 5000.0,
      "salePrice": 6000.0
    },
    "sale": null
  },
  {
    "id": 2,
    "quantity": 2,
    "product": {
      "id":2,
      "name": "Salchipapa Mixta2",
      "costPrice": 5000.0,
      "salePrice": 6000.0
    },
    "sale": null
  }
]

###
POST http://localhost:8090/api/product/all
Content-Type: application/json

{
  "name": "Salchipapa BBQ",
  "costPrice": 5000.0,
  "salePrice": 6000.0
}
###

POST http://localhost:8090/api/product/all
Content-Type: application/json

{
  "name": "Salchipapa Mixta",
  "costPrice": 4000.0,
  "salePrice": 5000.0
}
###


POST http://localhost:8090/api/person/all
Content-Type: application/json

{
  "name": "Carlos Ernesto Díaz Basante",
  "type": "Cliente",
  "address": "Mz G casa 5, los heroes",
  "phone": 3163930876,
  "email": "carlodiaz@umarian.edu.co"
}

###

POST http://localhost:8090/api/person/all
Content-Type: application/json

{
  "name": "Carlos Ernesto Díaz Basante",
  "type": "Cliente",
  "address": "Mz G casa 5, los heroes",
  "phone": 3163930876,
  "email": "carlodiaz@umarian.edu.co"
}

###

POST http://localhost:8090/api/person/all
Content-Type: application/json

{
  "name": "Carlos Ernesto Díaz Basante",
  "type": "Cliente",
  "address": "Mz G casa 5, los heroes",
  "phone": 3163930876,
  "email": "carlodiaz@umarian.edu.co"
}

###

POST http://localhost:8090/api/person/all
Content-Type: application/json

{
  "name": "Carlos Ernesto Díaz Basante",
  "type": "Cliente",
  "address": "Mz G casa 5, los heroes",
  "phone": 3163930876,
  "email": "carlodiaz@umarian.edu.co"
}

###
